### ISSUE TITLE
Does Nothing

### ISSUE THREAD

**Issue by timscott** [andyjeffries/ruby-string-interpolation#4]
I installed `ruby-string-interpolation`, and it does nothing.  I type `#` inside double quotes, and the curly braces do not appear. I select a segment of text inside double quotes then  type `#` and the hash character simply replaces the selected text.

I'm not seeing any errors in the tools console.  I have uninstalled and installed the package several times with Atom restarts in between. What more can I do to troubleshoot?

**Comment by sfroehler** [comment]
Same here...worked until a couple of weeks ago.

**Comment by deiga** [comment]
Same here, it used to work, but suddenly, nothing.

**Comment by deiga** [comment]
@andyjeffries ping

**Comment by andyjeffries** [comment]
Thanks for the ping, I'll have a look in to it.

**Comment by timscott** [comment]
I'm getting an error trying up update. It could be Atom, but it looks like the extension.

``` Javascript
Error serializing package 'ruby-string-interpolation' TypeError: Cannot read property 'serialize' of undefined
  at Object.module.exports.serialize (/Users/tscott/.atom/packages/ruby-string-interpolation/lib/ruby-string-interpolation.coffee:12:67)
  at Package.module.exports.Package.serialize (/Applications/Atom.app/Contents/Resources/app/src/package.js:393:97)
  at PackageManager.module.exports.PackageManager.deactivatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:132:65)
  at PackageManager.module.exports.PackageManager.update (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:177:23)
  at InstalledPackageView.module.exports.InstalledPackageView.installUpdate (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/installed-package-view.js:324:34)
  at HTMLSpanElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/installed-package-view.js:344:24)
  at HTMLSpanElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4676:9)
  at HTMLSpanElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4360:46)
```

**Comment by andyjeffries** [comment]
Just published 0.1.7, can you try that version please.

**Comment by timscott** [comment]
Same error. I also noticed that there are two errors (before and now).  The second one is:

``` Javascript
Uncaught TypeError: Cannot read property 'destroy' of undefined ruby-string-interpolation.coffee:9
module.exports.deactivate ruby-string-interpolation.coffee:9
module.exports.Package.deactivate /Applications/Atom.app/Contents/Resources/app/src/package.js:413
module.exports.PackageManager.deactivatePackage /Applications/Atom.app/Contents/Resources/app/src/package-manager.js:136
module.exports.PackageManager.update /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:177
module.exports.InstalledPackageView.installUpdate /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/installed-package-view…:324
(anonymous function) /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/installed-package-view…:344
jQuery.event.dispatch /Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4676
elemData.handle
```

**Comment by andyjeffries** [comment]
Just pushed v0.1.8, I don't get any errors with this version.  I understand how they were happening before, but the code is definitely not there now.

**Comment by timscott** [comment]
Seems good now. For the record, I did the following:
1. Updated to v0.1.8 -- got the same error
2. Quit and restarted Atom
3. Updated to v0.1.8 successfully
4. Tried typing `#` inside double quotes -- did nothing
5. Quit and restarted Atom
6. Tried typing `#` inside double quotes -- worked

Thanks!

**Comment by andyjeffries** [comment]
Don't know what all that restarting is about, but I guess some caching issues.  Glad it's all working for you now though.
