### ISSUE TITLE
Failed to activate the ruby-string-interpolation package

### ISSUE THREAD

**Issue by ScottDuke** [andyjeffries/ruby-string-interpolation#9]
[Enter steps to reproduce below:]
1. Within ""
2. pressing alt+3 to insert a # causes the issue and from there not able to insert a # when editing any document. 

**Atom Version**: 0.207.0
**System**: Mac OS X 10.10.3
**Thrown From**: [ruby-string-interpolation](https://github.com/andyjeffries/ruby-string-interpolation) package, v0.1.8
### Stack Trace

Failed to activate the ruby-string-interpolation package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
  at Object.module.exports.activate (/Users/sduke/.atom/packages/ruby-string-interpolation/lib/ruby-string-interpolation.coffee:6:23)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:238:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:770:25
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:219:20)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

```
### Commands

```
     -0:00.7.0 ruby-string-interpolation:insert (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "metrics"
    ],
    "projectHome": "/Users/sduke/repos/lcn/"
  }
}
```
### Installed Packages

``` coffee
# User
linter, v0.12.6
regex-railroad-diagram, v0.7.4
ruby-define-method, v0.2.1
ruby-string-interpolation, v0.1.8

# Dev
No dev packages
```

**Comment by nicpillinger** [comment]
+1 same issue here. although removing this package I still have #{} interpolation available so I'm guessing this has been rolled into the main ruby package now.

**Comment by Floppy** [comment]
+1 same here, couldn't type a # at all because of the error, As above though I've removed the package with no ill effects, so I guess it's unnecessary.

**Comment by mokolabs** [comment]
I'm also experiencing this issue on Atom 1.0.

I literally can't type a # sign when I press Shift - 3.

Maybe this package is using a deprecated Atom API?

**Comment by atalargo** [comment]
+1 for this issue too.

**Comment by atalargo** [comment]
To "fix" the error, i fork the project and create a new package for atom. 
This one includes the waiting PR for the keymap deprecated error too. I fix some other deprecate (menus, ...)
https://atom.io/packages/ruby-string-interpolation-atom-1
